sensitivity:
  Amphibian:
    1: Habitat specialisation
    2: Habitat specialisation
    3: Low Tolerance to temperature changes
    4: Tolerance of precipitation changes
    5: Dependence on an environmental trigger
    6: Increasing negative interactions with other species
  Bird:
    1: Habitat specialisation
    2: Microhabitat specialisation
    3: Intolerance of disturbance
    4: Low Tolerance to changes in precipitation regimes
    5: Low Tolerance to temperature changes
    6: Declining positive interactions with other species
    7: Small population size
    8: Small effective population size
  Mammal:
    1: Habitat specialisation
    2: Microhabitat specialisation
    3: Intolerant of disturbance
    4: Restricted to montane habitat
    5: Low Tolerance to changes in precipitation regimes
    6: Low Tolerance to temperature changes
    7: Low Tolerance to changes in fire regime
    8: Low Tolerance to flooding/waterlogging
    9: Reliability upon cue or trigger likely to be disrupted
    10: Dependence on narrow range of food types
    11: Interspecific habitat modification
    12: Increasing negative interactions

adaptability:
  Amphibian:
    1: Barriers to dispersal
    2: Barriers to dispersal
    3: Low reproductive capacity
  Bird:
    1: Extrinsic barriers to dispersal
    2: Low intrinsic dispersal capacity￼
    3: Low genetic diversity
    4: Slow turnover of generations
    5: Low reproductive capacity
  Mammal:
    1: Barriers to dispersal
    2: Barriers to dispersal
    3: Low intrinsic dispersal capacity
    4: Known low genetic diversity
    5: Low reproductive capacity / genetic turnover
