default: &default
  host: localhost
  encoding: unicode
  adapter: postgresql
  pool: 5
  timeout: 5000
  username: postgres
  database: parcc_development

development:
  <<: *default

test:
  <<: *default
  database: parcc_test

production:
  <<: *default
  database: parcc_production

staging:
  <<: *default
  database: parcc_staging
