# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

default: &default
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  protected_planet:
    root_url: "http://www.protectedplanet.net"
    blog_url: "http://blog.protectedplanet.net"
    parcc_search_path: "search?has_parcc_info=true&main=has_parcc_info"
    un_list_url: "http://wcmc.io/2014_un_list"

development:
  <<: *default

test:
  <<: *default

staging:
  <<: *default
  protected_planet_url: "http://stage.protectedplanet.net"

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  <<: *default
