# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c9a279e2a322b5734d6f83e6421ecba7c7c19d7a9515a2960a66b96ed502a55e0eb4f3b5395fe20557aaf28bb5fbbcc8801f5ffb5dbd80b6c0ddb54ebdcc4963

test:
  secret_key_base: 74353cd662ae8fdf7bb395167904b06a0fc5949b8ef2d5d64d0490a3a07c1fcaa380090d7d871a6ec3e5225a0d977790b2a7b3817a02a6e7fce35a6768bc5b0a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
